### PR TITLE
[Fix] Dependance

### PR DESCRIPTION
**Pull request by frju365**
PR mineure visant juste à fixer l'issue : #48 
*Minor decision*
- [ ] **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- [ ] **CI succeeded** :

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Can you use `ynh_install_app_dependencies` instead of apt install please ?
And update the remove script accordingly.

**Comment by frju365** [comment]
is it better ?

**Comment by JimboJoe** [comment]
You should update upgrade script as well.
And you don't need to pass parameters to the ynh_remove_dependencies script 😉

**Comment by frju365** [comment]
euh pourquoi l'upgrade ?

**Comment by JimboJoe** [comment]
Well, maybe there are already installed instances that don't work somewhere?
Furthermore, you should add this dependency in the restore script.

**Comment by Jibec** [comment]
as https://github.com/YunoHost-Apps/kanboard_ynh/pull/52 is rewriting this application, I also included the php5-gd dependency, I suggest to close this PR.

**Comment by frju365** [comment]
yes... this PR was pretty useless... and sorry... this PR was out of my mind.

**Comment by Jibec** [comment]
Le 23 octobre 2017 17:18:45 UTC+02:00, frju365 <notifications@github.com> a écrit :
>yes... this PR was pretty useless... and sorry... this PR was out of my
>mind.

This was useful, i totally forgot about deps :)
-- 
Jean-Baptiste Holcroft

**Pull request closed without merging**
