### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *The app doesn't use Fail2ban*

## Solution
- *Use fail2ban helper #75*
- *Upgrade to upstream version 1.2.8*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : frju365
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/kanboard_ynh%20testing%20(Official)/)

### CODE REVIEW

**Comment by kay0u** [comment]
Bump?

**Comment by JimboJoe** [comment]
Now open for reviews

**Comment by maniackcrudelis** [comment]
Checksum have changed since this PR !

**Comment by anmol26s** [comment]
Fixed and ready to be merged

**Comment by maniackcrudelis** [comment]
I'm worried though that the checksum has changed !

**Comment by anmol26s** [comment]
You mean it has changed again?

**Comment by JimboJoe** [comment]
Yes, it's worrying the checksum has changed while the release date and associated release commit are still 21 days ago... No information on this in the github issues or in the Kanboard forum.
I've tested the "new" testing with the checksum fixed by @anmol26s , and it's working OK, so I'm still in favour of merging that one.

**Comment by frju365** [comment]
about the checksum which change without explanation, it seems to be like the problem of garradin : dev recompress archive to update a security bug for exemple, and so it changes the checksum (perhaps I'm wrong)

I'm in favor of merging this PR.

**Comment by anmol26s** [comment]
Bump

**Comment by JimboJoe** [comment]
Will be merged in 3 days.

**Comment by JimboJoe** [comment]
Will be merged in 3 days.

**Comment by JimboJoe** [comment]
Need to advertise that new testing release.

**Comment by JimboJoe** [comment]
OK, let's review this testing to have a stable release (at last!) :sweat_smile:

**Comment by JimboJoe** [comment]
Will be released in 3 days.

**Pull request merged**
