### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Kanboard can't be upgraded on stretch*

## Solution
- *Add php-zip as a dependency #60*

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : JimboJoe from #60
- [x] **Approval (LGTM)** : JimboJoe from #60
- [x] **Approval (LGTM)** : jibec from #60, Josue-T, frju365
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/kanboard_ynh%20testing%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by Jibec** [comment]
good to see our process now works fine !

will we have the upgrade script launch in the stretch to jessie 
migration?
will it works fine with package version number?
do we have a a script to test this migration or is it a manual process?

**Comment by maniackcrudelis** [comment]
> good to see our process now works fine !

"now" ?

> will we have the upgrade script launch in the stretch to jessie migration?
will it works fine with package version number?

No, the upgrade script have to be launch by the user.
But it can't be any problem with the package version number, since this app doesn't use the helper to prevent an "useless" upgrade.

> do we have a a script to test this migration or is it a manual process?

If you mean a script to test the migration from jessie to stretch, yes we have. Have a look to the forum, Aleks has explained how to test that migration.

---
Josue-T, frju365, thanks for your approvals, but this PR is pending.
I made this PR in order to not forget that we have a testing ongoing, but until 7 days will be passed without issues or new commits, this PR have to be pending.
It's only after this time, for letting people try this testing, that we'll open this PR to reviews and merge it.

**Comment by maniackcrudelis** [comment]
Will be merged in 3 days

**Comment by maniackcrudelis** [comment]
Huh, is there a reason why we all have forgotten this PR !?

**Comment by maniackcrudelis** [comment]
So, let's say no then...

**Comment by frju365** [comment]
Indeed, there is no particular reason ;)

**Pull request merged**
