### PR TITLE
Fix stretch

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Kanboard can't be upgraded on stretch*

## Solution
- *Add php-zip as a dependency*

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Minor decision*
- [x] **Upgrade previous version** : JimboJoe
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : jibec
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/kanboard_ynh%20fix_stretch%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by Jibec** [comment]
LGTM
-- 
Jean-Baptiste Holcroft

**Comment by JimboJoe** [comment]
Will be merged in 3 days, then :wink:

**Comment by JimboJoe** [comment]
To be further discussed cf [this PR](https://github.com/YunoHost-Apps/nextcloud_ynh/pull/96)...

**Comment by maniackcrudelis** [comment]
Thank you, I knew there was another PR with php-zip, but I was not able to find it.
Anyway, I'm waiting for more information on the other topic before fixing this one.

**Comment by maniackcrudelis** [comment]
Wait for https://github.com/YunoHost-Apps/nextcloud_ynh/pull/96 to be merged, and then can be merged also.

**Comment by alexAubin** [comment]
37311966-933754aa-2649-11e8-8b74-8e0426b2e7e0

**Pull request merged**
