### PR TITLE
upgrade to 1.20, fix nginx issue, open jsonrpc for kandroid

### PR DESCRIPTION
**Pull request by Jibec**
only tested with package_check, please have a look with real installs, i'll do the same on my server soon

## Problem
- *Description of why you made this PR*

## Solution
- *And how you fix that*

## PR Status
*Obviously, you should really check these affirmations*  
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Minor decision*
- [x] **Upgrade previous version** : Maniack C
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : Maniack C
- [x] **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/kanboard_ynh%20PR55%20(Official_fork)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by Jibec** [comment]
tested with package_check and VM upgrade, works fine.
I have no plugins, only a few projects with a few hundreds tasks

**Comment by JimboJoe** [comment]
LGTM, code review and upgrade from previous version OK... except for the Kandroid part: I didn't manage to login from Kandroid...
I guess you need to use `skipped_uris` instead of `unprotected_uris` as in [ttrss](https://github.com/YunoHost-Apps/ttrss_ynh/blob/master/scripts/install#L146).

**Comment by Jibec** [comment]
can we go forward? The connection bug is not related to Kanboard: https://github.com/andresth/Kandroid/issues/38

**Comment by JimboJoe** [comment]
Didn't we need to activate LDAP authentication...?

**Comment by maniackcrudelis** [comment]
Code review OK and LGTM

**Comment by maniackcrudelis** [comment]
Will be merged in 3 days.

**Comment by maniackcrudelis** [comment]
By the way, it could be really interesting to have a way to keep traces of the previous maintainers.
I can understand that now jibec is becoming the main maintainer, but it would be really nice to keep mbugeia somewhere too.

**Comment by Jibec** [comment]
if you tell me how to do it, I'll be pleased to add previous maintainer name as an INFO in the manifest.json, but I doubt this file aim to keep historic data. I would rather keep it somewhere else (like Readme, but we don't need structured data for this).

**Comment by maniackcrudelis** [comment]
I opened a issue about that, https://dev.yunohost.org/issues/1095
Let's talk about how handle this over there.

For the moment, an upgrade of kanboard could be interresting and should not be stopped by that.
This field is about the current maintainer, and we have to keep it clear to allow users to ask to the real (and current) maintainer of an app.

As this PR has been accepted, I merge it.

**Comment by maniackcrudelis** [comment]
> if you tell me how to do it, I'll be pleased to add previous maintainer name as an INFO in the manifest.json, but I doubt this file aim to keep historic data. I would rather keep it somewhere else (like Readme, but we don't need structured data for this).

Following our meeting this evening, the idea is to try a new entry in the manifest called "old_maintainers" or "previous_maintainers", which should not causes any trouble to the manifest.
I like the idea to keep this information just next to the current maintainer.

**Pull request merged**
