### PR TITLE
add missing dependencies

### PR DESCRIPTION
**Pull request by plopoyop**
## Problem
- When installing kanboard, I had  a missing mbstring extension. After installing it manually, I had a missing dom extension. error. 
## Solution
- Used php- instead of php7-, it is more generic. php-dom is a alias for php-xml.

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : Josué
- **CI succeeded** : 

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/kanboard_ynh%20PR71%20(Official_fork)/) 
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
php-gd, php-dom and php-mbstring are only available on stretch.
This packages should be included in the 'if' below.
As php-dom is an alias of php-xml, why not using php-xml ?

Also, this modification should be made as well in the restore script and the upgrade script.

**Comment by plopoyop** [comment]
Since we have to make the same change 3 times maybe I can move this into a function in _common.sh

Is jessie still maintained ? In this case, it could be better to do something like : 
```
if [ "$(lsb_release --codename --short)" == "jessie" ]; then
	pkg_dependencies="php5-gd"
else
	pkg_dependencies="php-gd php-zip php-dom php-mbstring"
fi
ynh_install_app_dependencies $pkg_dependencies
```

Php is complaining about the missing extension php-dom. Today it is an alias for php-xml. I don't know how it is going to be in the future. I prefer to use the one that is missing and not the one that is aliased.

**Comment by maniackcrudelis** [comment]
$pkg_dependencies can be defined in _common.sh, as other apps. Without any function.

Jessie is, at least, still used by many users. But reverse the if could be a good idea.

**Comment by maniackcrudelis** [comment]
Code review OK

**Comment by JimboJoe** [comment]
Will be merged in 3 days.

**Pull request merged**
