### PR TITLE
Instructions in Readme: How to use non SSOwat users

### PR DESCRIPTION
**Pull request by lapineige**
## Problem
This solve a common issue.
See for instance: https://github.com/YunoHost-Apps/kanboard_ynh/issues/68

## Solution
The Readme contains the information to correct that.

## PR Status
- [x] Code finished.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : frju365
- [x] **Approval (LGTM)** : frju365
- [x] **Approval (LGTM)** : Maniack C
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/kanboard_ynh%20-BRANCH-%20(Official)/) *Please replace '-BRANCH-' in this link for a PR from a local branch.*  
or  
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/kanboard_ynh%20PR-NUM-%20(Official_fork)/) *Replace '-NUM-' by the PR number in this link for a PR from a forked repository.*  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by lapineige** [comment]
(thanks for the typo fix, I should read over my writing 😅)

**Comment by anmol26s** [comment]
Sorry to reply after the reviews have been approved. But there is a misunderstanding, I think. I was not able to login through SSO/Ldap after the fresh install. And there was no way to create external account as I was not able to login by SSO/Ldap admin account. So I was totally blocked to get into Kanboard by any means. After making **REVERSE_PROXY_AUTH** to **false**, I was able to login by Ldap account and from admin account I could create an external account too, which can be logged in as normal external users.
So actually I wanted to know if anyone else is facing this issue and gave suggestion to make **REVERSE_PROXY_AUTH**  permanently **false**.

Therefore this statement https://github.com/YunoHost-Apps/kanboard_ynh/issues/68#issuecomment-397815792 don't stand true in my case because the Ldap setting has not been disabled in the config file and Ldap works along with the external accounts for me.

**Comment by lapineige** [comment]
Wow, that's strange, I saw this explanation (you can't have both login methods at the same time, you need to change this parameter) on Yunohost forum, and after installing I was able to log with my Yunohost account (and no external account), while it's the contrary after switching this parameter to false.

**Comment by maniackcrudelis** [comment]
It's only about a readme.
Let's merge in 3 days, if no one disagree.

**Pull request merged**
