### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- *Upgrade to upstream version 1.2.18*
- *Set cronjob permissions to 644*
- *Fix linter warning*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/kanboard_ynh%20PR106%20(ericgaspar)/)

### CODE REVIEW

**Comment by JimboJoe** [comment]
The rendering is broking due to CSP changes; excerpt from browser console:
```
ortest.local/:1 Unrecognized Content-Security-Policy directive 'self'.

ortest.local/:1 Unrecognized Content-Security-Policy directive 'unsafe-eval'.

ortest.local/:1 Unrecognized Content-Security-Policy directive 'data'.

ortest.local/:12 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src ". Either the 'unsafe-inline' keyword, a hash ('sha256-6WvsU/s7NHr7vgDCAdRA1w+pC2KSOQ9tARvq3hnjIZc='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

5Refused to load the stylesheet '<URL>' because it violates the following Content Security Policy directive: "default-src ". Note that 'style-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

ortest.local/:1 Refused to load the script 'https://ortest.local/kanboard/assets/js/vendor.min.js?1609107091' because it violates the following Content Security Policy directive: "default-src ". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

ortest.local/:1 Refused to load the script 'https://ortest.local/kanboard/assets/js/app.min.js?1609107091' because it violates the following Content Security Policy directive: "default-src ". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

6Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "default-src ". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

ortest.local/:1 Refused to load the script 'https://ortest.local/ynh_portal.js' because it violates the following Content Security Policy directive: "default-src ". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

ortest.local/:1 Refused to load the script 'https://ortest.local/ynhtheme/custom_portal.js' because it violates the following Content Security Policy directive: "default-src ". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

ortest.local/:61 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src ". Either the 'unsafe-inline' keyword, a hash ('sha256-cym71Zv3cTbIedljE5txz0dprgICZxta8sKdZG6TGc0='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

ortest.local/:306 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src ". Either the 'unsafe-inline' keyword, a hash ('sha256-cym71Zv3cTbIedljE5txz0dprgICZxta8sKdZG6TGc0='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by ericgaspar** [comment]
:)  Thats me trying to get the CSP formating right in NGINX...
It should work now.

**Review by JimboJoe — APPROVED** [review]
LGTM and upgrade tested OK 👍

**Review by JimboJoe — APPROVED** [review]
LGTM and upgrade tested OK 👍

**Comment by ericgaspar** [comment]
My previous commit fixes error on Firefox console but not in Chromium... So for now I am gonna leave `more_set_headers` setting unchanged...

**Pull request merged**
