### PR TITLE
Upgrade to upstream version 1.2.9

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *The application is not up-to-date*

## Solution
- *Update to latest version 1.2.9*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : Kay0u
- **CI succeeded** : 
[Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/kanboard_ynh%20PR80/)
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Will be merged in 3 days.

**Comment by maniackcrudelis** [comment]
I see a lot of test on this app from the dev CI.
JimboJoe are you working on the corrupt source error ?

**Comment by JimboJoe** [comment]
Nope, can the tests auto-spawn...?

**Comment by maniackcrudelis** [comment]
I don't think so...
But I have recently changed the way the CI is getting update from github, by using github API.
Even though, I can't see any relation...

That's indeed the second time, and still the release didn't change on github.
I wonder if it's possible to update a release within the same release. But there's actually no new commit since the release on kanboard repo, except the translation, which isn't in the release.

That's strange, and worrying...

**Comment by JimboJoe** [comment]
Now the build is passing, but the CI is still looping...

**Comment by maniackcrudelis** [comment]
There's an error somewhere.
I see in the log "Switched to a new branch" each time the script runs. Same for piwigo...

**Comment by maniackcrudelis** [comment]
Found it, an error in the branch name during the remove part of the script.
It was matching ".9" at the end of the branch name.

Fixed by https://github.com/YunoHost/CI_package_check/commit/cc3145eb181c5b3226558af48a056a41b9c87209

Bash pattern is a ERE, not PCRE. And even with ERE, it's not really working.

**Comment by JimboJoe** [comment]
So... can this PR be merged?

**Comment by maniackcrudelis** [comment]
Can be merged in 3 days

**Pull request merged**
